### PR TITLE
Fix function getGlobalScoreList into setGlobalScore

### PR DESCRIPTION
**Pull request by junman95**
# Pull Request Template

## Type of PR

- [ ] Feature - Platform
- [ ] Feature - Game
- [x] Fix - Bug

## Description of PR
- wrong function naming which posts new score is written as a 'getGlobalScoreList'

## Changes Made
- file name change
- unused import and vars erased

## Checklist

- [x] Prepared for code review (Assignees set, Labels applied, etc.)
- [x] Checked that changes do not negatively affect existing features
- [ ] Documentation completed for new features
- [x] All unit tests passed
- [x] Testing in the test environment completed
- [ ] Linked this PR in the related issue
- [ ] Communicated sufficiently with the relevant team or person before submitting PR

### CODE REVIEW

**Comment by junman95** [comment]
needs to be merged after #58

**Comment by XPECTER** [comment]
There is a commit identical to #58. I think you have to be careful not to get it twist the branch

**Comment by Ooyd** [comment]
#58 approved. Merging can proceed as outlined in the PR description. 
Thanks for addressing the incorrect naming issue.
Also, #58 #59 both modify global-score-board-provider file.
Ensure to check for conflicts to avoid a branch crash during merging.

**Review by Ooyd — APPROVED** [review]

**Comment by junman95** [comment]
> There is a commit identical to #58. I think you have to be careful not to get it twist the branch

Understood

**Pull request merged**
