### PR TITLE
feat: Compile TypeScript and Implement Dynamic Addition of WebView Sidebar Icons

### PR DESCRIPTION
**Pull request by Ooyd**
# Pull Request Template

## Type of PR

- [x] Feature - Platform
- [x] Feature - Game
- [ ] Fix - Bug

## Description of PR
- A TypeScript to JavaScript compilation process
- The implementation of dynamic logic to add icons to the WebView sidebar.

https://github.com/hp-potion/vsc-gameboy/assets/22022776/9f3af345-c040-47a7-9987-a70481242b74

## Changes Made
- Developed and integrated a TypeScript to JavaScript compilation workflow
- Engineered dynamic logic for adding icons to the WebView sidebar

## Checklist

- [x] Prepared for code review (Assignees set, Labels applied, etc.)
- [x] Checked that changes do not negatively affect existing features
- [ ] Documentation completed for new features
- [ ] All unit tests passed
- [ ] Testing in the test environment completed
- [ ] Linked this PR in the related issue
- [x] Communicated sufficiently with the relevant team or person before submitting PR

### CODE REVIEW

**Comment by junman95** [comment]
Well done.
I have sent an email to Mr.Karen, owner of js-tetris repository for a permission.

**Review by junman95 — APPROVED** [review]

**Review by XPECTER — APPROVED** [review]

**Comment by XPECTER** [comment]
Thank you for your efforts.

**Comment by smshack** [comment]
funtion is good

**Comment by junman95** [comment]
> Well done. I have sent an email to Mr.Karen, owner of js-tetris repository for a permission.

image

**Pull request merged**
